### ISSUE TITLE
Quantum memory game

### ISSUE THREAD

**Issue by desireevl** [quantum-melbourne/qiskit-hackathon-22#1]
# Abstract

A memory game (based on the memory game involving cards, matching two of the same cards) aimed to help you learn about quantum computing. Create a playable memory game, hosted locally or online, using Python, the Qiskit library and Qiskit simulators/real devices.

# Description 

Example ideas for the game play:
- Cards that are in superposition state that can change when you click it (you have to get lucky to match)
- Cards won't be exactly the same - some will have a picture of a circuit on it and you have to match the ones that result in the same output state
- Use Qiskit to randomise position of cards
- Versus mode - if you match correctly you get an advantage/opponent gets disadvantage (for example, random time decrease)
- Team can think of other interesting cards to use and other good ways to incorporate Qiskit simulator

Here are some links to some memory game templates in Python, that could potentially be used as a foundation for the card game and modified to fit your purpose:
- https://github.com/AuroraDark/jogo_da_memoria
- https://github.com/loetcodes/Fringe_MemoryGame
- https://github.com/e-vdb/Memory-game
- https://github.com/penguintutor/memorygame

# Members

 - Qiskit Coach: @desireevl 

# Deliverable

A playable memory card game, hosted either online, or locally.

# GitHub repo

**Comment by MingCHEN-Github** [comment]
interesting

**Comment by MingCHEN-Github** [comment]
May I join in?

**Comment by desireevl** [comment]
@MingCHEN-Github I am at the corner table if you are interested for a chat!
