### ISSUE TITLE
Quantum Twitter Sentiment Analysis

### ISSUE THREAD

**Issue by peiyong-addwater** [quantum-melbourne/qiskit-hackathon-22#4]
# Abstract
Classic beginner's task for machine learning/natural language processing, but **Quantum!**

If you are doing NLP research or would like to dive into the world of NLP, this is your chance to experience something totally new. 

![do you guys just put quantum in front of everything](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDAMlSE2F-iefYGiFdyRkC7etrT1VGGHWACFMafbRSv8StWTulyzeuQ8JG-UDI0ywix64&usqp=CAU)

# Description 

Maybe you have done this multiple times, but I promise you, this time it will be different!

We will need to find a way to load the Twitter texts onto the quantum computer/simulator, and then develop a (simple) model to classify the sentiments expressed in the tweets.  We'll be using a small subset of the open-source dataset, like the [Sentiment140](https://www.kaggle.com/datasets/kazanova/sentiment140) dataset (or any other opensource dataset on Kaggle), and a good example of how to preprocess the data and analyse the sentiment in the traditional way can be found [here](https://www.kaggle.com/code/stoicstatic/twitter-sentiment-analysis-for-beginners). For modelling language with quantum computers, we'll try to follow a series of techniques developed by Bob Coecke and friends, see the tutorial of the [lambeq](https://github.com/CQCL/lambeq) Python package [here](https://cqcl.github.io/lambeq/tutorials/sentence-input.html).  An interesting talk about quantum natural language processing by Bob can be found [here](https://www.youtube.com/watch?v=6-uKZN5_eAU). An example of how Bob's QNLP framework process the sentence can be found at a [Jupyter Notebook](https://github.com/peiyong-addwater/Hackathon-QNLP/blob/main/UdemyQNLPCourse/Sentence%2BClassification%2BClassical%2Band%2BQuantum/MM_MC_QNLP_Quantum_Piepline_tket.ipynb) modified from the Udemy QNLP course material. Anonther example of converting sentence to diagrams can be seen ![here](https://github.com/peiyong-addwater/Hackathon-QNLP/blob/main/DarthPlagueisTheWise.png).

# Environment/Installation
Although you can just pip install the required packages (lambeq, spacy, allennlp, pytket, ...), I prepared docker images for everything we need. If you are familiar with/want to try docker, go to [https://hub.docker.com/repository/docker/addwater0315/quantum](https://hub.docker.com/repository/docker/addwater0315/quantum) to pull the image tagged with **qnlp** or **qnlp_gpu** for GPU-enabled machines that have NVdia container toolkit installed.

# Goals
Through this project, we would like to learn the techniques of quantum natural language processing together, and show you how quantum can transform other areas, in this case, linguistics and natural language processing.
- Develop a basic understanding of how to handle basic NLP tasks on a quantum computer;
- Familiar with the basics of the DisCoCat algorithm;
- Discover new possibilities of combining current NLP research with QNLP techniques.

# Useful Links
- [Near-Term Advances in Quantum Natural Language Processing](https://arxiv.org/abs/2206.02171)
- [lambeq: An Efficient High-Level Python Library for Quantum NLP](https://arxiv.org/abs/2110.04236)
- [Foundations for Near-Term Quantum Natural Language Processing](https://arxiv.org/abs/2012.03755)
- [A gentle introduction to Quantum Natural Language Processing](https://arxiv.org/abs/2202.11766)
- [[1904.03478] The Mathematics of Text Structure - arXiv](https://arxiv.org/abs/1904.03478)
- [Quantum Natural Language Processing on Near-Term Quantum Computers](https://arxiv.org/abs/2005.04147)
- [[2107.06776] How to make qubits speak - arXiv](https://arxiv.org/abs/2107.06776)
- [Quantum Natural Language Processing - Medium](https://medium.com/cambridge-quantum-computing/quantum-natural-language-processing-748d6f27b31d)
- [An Introduction to Quantum Natural Language Processing (Udemy)](https://www.udemy.com/course/quantum-natural-language-processing-beginners/)
There also has been some exciting research on generating and classifying music with QNLP techniques, see:
- [CQCL/Quanthoven - GitHub](https://github.com/CQCL/Quanthoven)
- [Ludovico Quanthoven | SoundClick](https://www.soundclick.com/LudovicoQuanthoven)
- [A Quantum Natural Language Processing Approach to Musical Intelligence](http://arxiv.org/abs/2111.06741)
An example of applying QNLP to text classification can be found [here](https://github.com/ACE07-Sev/QNLP).

# Members

 
 
 - Qiskit Coach: @peiyong-addwater - email: peiyongw@student.unimelb.edu.au - Twitter: [@peiyong_wang](https://twitter.com/peiyong_wang)
 - Group Member: @731935354, @ruixing76

# Deliverable
[A (short) presentation depicting our algorithm and data processing pipeline.](https://github.com/peiyong-addwater/Hackathon-QNLP/blob/main/Presentation.pdf)

# GitHub repo

See [https://github.com/peiyong-addwater/Hackathon-QNLP](https://github.com/peiyong-addwater/Hackathon-QNLP).

**Comment by 731935354** [comment]
I will join your team!

**Comment by ruixing76** [comment]
I will join:)

**Comment by peiyong-addwater** [comment]
[Presentation.pdf](https://github.com/quantum-melbourne/qiskit-hackathon-22/files/9060461/Presentation.pdf)

**Comment by peiyong-addwater** [comment]
closing this issue
