### ISSUE TITLE
Quantum Chemistry Simulations using Entanglement Forging

### ISSUE THREAD

**Issue by cnakhl** [quantum-melbourne/qiskit-hackathon-22#5]
# Abstract
One of the main applications of Quantum Computing is for Chemistry simulations, unfortunately though many of the simulations we want to do require too many qubits. Let's try and do something about that....

# Description
[Entanglement Forging](https://arxiv.org/abs/2104.10220) is a procedure that was recently proposed that halves the number of qubits required to perform simulations of an N qubit system on a quantum computer. The procedure has been used to perform simulations of the ground state of the water molecule using the Variational Quantum Eigensolver (VQE) algorithm. 

This project will explore the mechanics underpinning the entanglement forging procedure and try to explore further optimisations and/or improvements which may allow for us to further shrink the qubit required to perform Quantum Chemistry simulations. 

You can find a prototype of entanglement forging which was coded up by the original authors [here](https://github.com/qiskit-community/prototype-entanglement-forging)

We may also use [this](https://quimb.readthedocs.io/en/latest/) library to explore/implement Matrix Product States (MPS), a tensor network which is analogous to the mathematics underpinning the entanglement forging procedure. 

We will go through a quick crash course of the theory required at the start of the project so don't worry if you don't know anything about entanglement forging, VQE, or tensor networks and don't know where to begin.

# Members
 - Qiskit Coach: @cnakhl - email: a.nakhl@student.unimelb.edu.au
 - @qsukhi
 - @llama-hedge

# Deliverable
- A Python module which executes entanglement forging (including any improvements we come up with) for some given system
- A short presentation outlining our implementation of the procedure and the results from all the molecules we simulated

**Comment by qsukhi** [comment]
I'm interested! qsukhi@gmail.com

**Comment by attp** [comment]
This qiskit entanglement forging prototype might be useful to this team: https://github.com/qiskit-community/prototype-entanglement-forging

**Comment by llama-hedge** [comment]
I want to join this one

**Comment by mbunn28** [comment]
Hello Chris I would like to participate in the Quantum Chemistry please

**Comment by cnakhl** [comment]
[Uploading ent_forging.pdf…]()

**Comment by cnakhl** [comment]
[ent_forging.pdf](https://github.com/quantum-melbourne/qiskit-hackathon-22/files/9060524/ent_forging.pdf)

**Comment by desireevl** [comment]
@cnakhl I'm just wondering if the link you posted to your Github repo is private or has it been deleted? I am writing a blog post and would love to share your work!

**Comment by cnakhl** [comment]
> @cnakhl I'm just wondering if the link you posted to your Github repo is private or has it been deleted? I am writing a blog post and would love to share your work!

It has been deleted as the project's code wasn't managed in git in the end.
